version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  app:
    image: historialmedico:latest
    container_name: historialmedico-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/HistorialMedico
    depends_on:
      - mongodb
    entrypoint: ["sh", "-c", "sleep 10 && java -jar /app/app.jar"]
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
    driver: bridge
